#!/bin/bash

rm -f docs/*.md

# The relative location of the facetjs repo
# They should live side by side
facetjs="../facetjs"

docs=`ls $facetjs/docs/*.md | sed s:$facetjs/docs/::`

for doc in $docs
do
  cp docs.md.part docs/$doc

  # Make markdown links workable by removing the ".md" extension
  sed s/\.md\)/\)/ $facetjs/docs/$doc >> docs/$doc;
done
